### ISSUE TITLE
[request] ability to disable items in the config file on a per item basis.

### ISSUE THREAD

**Issue by majijn** [Terrails/Ingotter#2]
I dont want several of the nuggets, and a couple of the tool sets and plates/wires, but from what I see in the config file disabling tools ,nuggets and plates means disabling all of them.

**Comment by Terrails** [comment]
Won't add it since it would take me a lot of time to do that since I need to edit each recipe json file (271 currently) and add a condition to each, otherwise if you disable a item it would throw errors how the item doesn't exist. You could get the same thing by just hiding the items in JEI/NEI and disabling their recipes with CraftTweaker
